AuxiPress_Project/Areas/Admin/Controllers/CarTypeController.cs
using AuxiPress.DAL;
using AuxiPress.DAL.Repository.IRepository;
using AuxiPress.Models;
using Microsoft.AspNetCore.Mvc;

namespace AuxiPress_Project.Controllers
{
    [Area("Admin")]
    public class CarTypeController : Controller
    {
        private readonly IUnitOfWork _unitOfWork; 
        public CarTypeController(IUnitOfWork unitOfWork) 
        {
            _unitOfWork = unitOfWork; 
        }

        public IActionResult Index()
        {
            IEnumerable<CarType> objCarTypeList = _unitOfWork.CarType.GetAll(); 
            return View(objCarTypeList);
        }

        //GET
        public IActionResult Create()
        {
            return View(); 
        }
        //POST
        [HttpPost]
        [ValidateAntiForgeryToken] 
        public IActionResult Create(CarType obj) 
        {
            if(ModelState.IsValid) 
            {
                _unitOfWork.CarType.Add(obj); 
                _unitOfWork.Save(); 
                TempData["Success"] = "CarType Created Succesfully"; 
                return RedirectToAction("Index"); 
            }
            return View(obj);
        }

        //GET
        public IActionResult Edit(int? id)
        {
            if(id==null || id==0)
            {
                return NotFound();
            }
            
            var carTypeFromDbFirst = _unitOfWork.CarType.GetFirstOrDefault(u=>u.Id==id); 

            if(carTypeFromDbFirst == null) 
            {
                return NotFound();
            }
            return View(carTypeFromDbFirst);
        }
        //POST
        [HttpPost]
        [ValidateAntiForgeryToken] 
                                   
        public IActionResult Edit(CarType obj) 
        {

            if (ModelState.IsValid) 
            {
                _unitOfWork.CarType.Update(obj); 
                _unitOfWork.Save(); 
                TempData["Success"] = "CarType Updated Succesfully";
                return RedirectToAction("Index"); //Je redirige directement sur ma mon Index qui affiche mon tableau
            }
            return View(obj);
        }

        //GET
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
           
            var carTypeFromDbFirst = _unitOfWork.CarType.GetFirstOrDefault(u => u.Id == id);

            if (carTypeFromDbFirst == null) 
            {
                return NotFound();
            }
            return View(carTypeFromDbFirst);
        }
        //POST
        [HttpPost]
        [ValidateAntiForgeryToken] 
                                   
        public IActionResult DeletePost(int? id) 
        {
            var obj = _unitOfWork.CarType.GetFirstOrDefault(u => u.Id == id);
            if (obj == null)
            {
                NotFound();
            }

            _unitOfWork.CarType.Remove(obj); 
            _unitOfWork.Save(); 
            TempData["Success"] = "CarType Deleted Succesfully";
            return RedirectToAction("Index"); 
            
        }
    }
}

AuxiPress_Project/Areas/Admin/Controllers/CategoryController.cs
using AuxiPress.DAL;
using AuxiPress.DAL.Repository.IRepository;
using AuxiPress.Models;
using Microsoft.AspNetCore.Mvc;

namespace AuxiPress_Project.Controllers
{
    [Area("Admin")]
    public class CategoryController : Controller
    {
        private readonly IUnitOfWork _unitOfWork; //Grâce a l'injection de dépendance, je ne dois pas créer un objet de la classe AppDbContext et l'initialiser!

        public CategoryController(IUnitOfWork unitOfWork) //Je demande au constructeur d'utiliser mon UnitOfWork pour accéder a la database
        {
            _unitOfWork = unitOfWork; //J'ai maintenant mon UnitOfWork avec l'injection de dépendance
        }

        public IActionResult Index()
        {
            IEnumerable<Category> objCategoryList = _unitOfWork.Category.GetAll(); //j'accède a ma Db via _db je récupère mes Categories que je place dans ma IEnumerable objCategoryList!!
            return View(objCategoryList);
        }

        //GET
        public IActionResult Create()
        {
            return View(); //Je laisse mon Create Vide car et je vais créer mon modèle directement dans ma vue!
        }
        //POST
        [HttpPost]
        [ValidateAntiForgeryToken] //Un token qui permet de bloquer des attaques sur
                                   //les formulaires en injectant une clé qui sera valider ici
        public IActionResult Create(Category obj) //Il recevra en paramètre un objet de type Category
        {
            if(obj.Name == obj.DisplayOrder.ToString())
            {
                ModelState.AddModelError("name", "Display order should be different from the Name"); //Erreur Customisé
            }
            if(ModelState.IsValid) //Validation coté serveur avec l'outil intégré ModelState.IsValid (Notre name est Obligatoire !)
            {
                _unitOfWork.Category.Add(obj); //J'utilise ma méthode Add de IUnitOfWork
                _unitOfWork.Save(); //Cela va sauvegarder les données dans ma base de donnée SQL
                TempData["Success"] = "Category Created Succesfully"; /*Je crée un petit Message style Alerte avec un TempData!*/
                return RedirectToAction("Index"); //Je redirige directement sur ma mon Index qui affiche mon tableau
            }
            return View(obj);
        }

        //GET
        public IActionResult Edit(int? id)
        {
            if(id==null || id==0)
            {
                return NotFound();
            }
            //var categoryFromDb = _db.Categories.Find(id); 
            var categoryFromDbFirst = _unitOfWork.Category.GetFirstOrDefault(u=>u.Id==id); //En parametre de ma méthode GetFirstOrDefault j'ai spécifié qu'il accpete les fonctions fléchés

            if(categoryFromDbFirst == null) //Je check qu'il soit pas nul
            {
                return NotFound();
            }
            return View(categoryFromDbFirst);
        }
        //POST
        [HttpPost]
        [ValidateAntiForgeryToken] //Un token qui permet de bloquer des attaques sur
                                   //les formulaires en injectant une clé qui sera validee ici
        public IActionResult Edit(Category obj) //Il recevra en paramètre un objet de type Category
        {
            if (obj.Name == obj.DisplayOrder.ToString())
            {
                ModelState.AddModelError("name", "Display order should be different from the Name"); //Erreur Customisé
            }
            if (ModelState.IsValid) //Validation coté serveur avec l'outil intégré ModelState.IsValid (Notre name est Obligatoire !)
            {
                _unitOfWork.Category.Update(obj); //Grâce au Update déjà mis en place via Entity Framework je met à jour ma DB!!
                _unitOfWork.Save(); //Cela va sauvegarder les données dans ma base de donnée SQL
                TempData["Success"] = "Category Updated Succesfully";
                return RedirectToAction("Index"); //Je redirige directement sur ma mon Index qui affiche mon tableau
            }
            return View(obj);
        }

        //GET
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            //var categoryFromDb = _db.Categories.Find(id);
            var categoryFromDbFirst = _unitOfWork.Category.GetFirstOrDefault(u => u.Id == id);

            if (categoryFromDbFirst == null) //Je check qu'il soit pas nul
            {
                return NotFound();
            }
            return View(categoryFromDbFirst);
        }
        //POST
        [HttpPost]
        [ValidateAntiForgeryToken] //Un token qui permet de bloquer des attaques sur
                                   //les formulaires en injectant une clé qui sera valider ici
        public IActionResult DeletePost(int? id) //Il recevra en paramètre un objet de type Category
        {
            var obj = _unitOfWork.Category.GetFirstOrDefault(u => u.Id == id);
            if (obj == null)
            {
                NotFound();
            }

            _unitOfWork.Category.Remove(obj); //Grâce au Update déjà mis en place via Entity Framework je met à jour ma DB!!
            _unitOfWork.Save(); //Cela va sauvegarder les données dans ma base de donnée SQL
            TempData["Success"] = "Category Deleted Succesfully";
            return RedirectToAction("Index"); //Je redirige directement sur ma mon Index qui affiche mon tableau
            
        }
    }
}

AuxiPress_Project/Areas/Admin/Controllers/ProductController.cs
using AuxiPress.DAL;
using AuxiPress.DAL.Repository.IRepository;
using AuxiPress.Models;
using AuxiPress.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace AuxiPress_Project.Controllers
{
    [Area("Admin")]
    public class ProductController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _hostEnvironment;
        public ProductController(IUnitOfWork unitOfWork, IWebHostEnvironment hostEnvironment)
        {
            _unitOfWork = unitOfWork;
            _hostEnvironment = hostEnvironment;
        }

        public IActionResult Index()
        {
            return View();
        }

        //GET

        public IActionResult Upsert(int? id) //Une seule méthode pour Update & Insert
        {
            ProductViewModel productVM = new()
            {
                Product = new(),
                CategoryList = _unitOfWork.Category.GetAll().Select(i => new SelectListItem
                {
                    Text = i.Name,
                    Value = i.Id.ToString()
                }),

                CarTypeList = _unitOfWork.CarType.GetAll().Select(i => new SelectListItem
                {
                    Text = i.Name,
                    Value = i.Id.ToString()
                }),

            };

            if(id != null && id > 0)
            {
                //Update product
                productVM.Product = _unitOfWork.Product.GetFirstOrDefault(u => u.Id == id);
                

            }
            return View(productVM);
        }
        //POST
        [HttpPost]
        [ValidateAntiForgeryToken] 
                                   
        public IActionResult Upsert(ProductViewModel obj, IFormFile? file) //J'ai rajouté IFormeFile qui me permet de recevoir en paramètre un upload de fichier
        {

            if (ModelState.IsValid) 
            {
                string wwwRoothPath = _hostEnvironment.WebRootPath; //Je récupère la route du wwwroot
                if(file != null) //je vérifie si il est nul
                {
                    string fileName = Guid.NewGuid().ToString(); //Je génère un nv nom de fichier afin d'éviter des soucis de fichiers portant le même nom!
                    var uploads = Path.Combine(wwwRoothPath, @"lib\");
                    var extension = Path.GetExtension(file.FileName); //je garde la même extension!

                    //Je m'assure d'effacer l'ancienne image si elle existe(dans le cas d'un update!)
                    if(obj.Product.ImageURL != null)
                    {
                        var oldImagePath = Path.Combine(wwwRoothPath, obj.Product.ImageURL.TrimStart('\\'));
                        if(System.IO.File.Exists(oldImagePath))
                        {
                            System.IO.File.Delete(oldImagePath);
                        }
                    }

                    using (var fileStreams = new FileStream(Path.Combine(uploads, fileName+extension), FileMode.Create))
                    {
                        file.CopyTo(fileStreams);
                    }
                    obj.Product.ImageURL = @"lib\" + fileName + extension; //Je le rajoute dans DB
                }

                if(obj.Product.Id == 0)
                {
                    _unitOfWork.Product.Add(obj.Product);
                }
                else
                {
                    _unitOfWork.Product.Update(obj.Product);
                }

                _unitOfWork.Save(); 
                TempData["Success"] = "Product Created Succesfully";
                return RedirectToAction("Index"); //Je redirige directement sur ma mon Index qui affiche mon tableau
            }
            return View(obj);
        }



        //API EndPoint
        //GET
        #region API Calls 
        [HttpGet]
        public IActionResult GetAll()
        {
            var productList = _unitOfWork.Product.GetAll(includeProperties:"Category,CarType");
            return Json(new {data = productList});
        }

        //POST
        [HttpDelete]
        public IActionResult Delete(int? id)
        {
            var obj = _unitOfWork.Product.GetFirstOrDefault(u => u.Id == id);
            if (obj == null)
            {
                return Json(new { success = false, message = "Error while deleting" });
            }

            var oldImagePath = Path.Combine(_hostEnvironment.WebRootPath, obj.ImageURL.TrimStart('\\'));
            if (System.IO.File.Exists(oldImagePath))
            {
                System.IO.File.Delete(oldImagePath);
            }

            _unitOfWork.Product.Remove(obj);
            _unitOfWork.Save();
            return Json(new { success = true, message = "Delete Successful" });

        }
        #endregion

    }


}

AuxiPress_Project/Areas/Customer/Controllers/CartController.cs
using AuxiPress.DAL.Repository.IRepository;
using AuxiPress.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace AuxiPress_Project.Areas.Customer.Controllers
{
    [Area("Customer")]
    [Authorize]
    public class CartController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public int OrderTotal { get; set; }
        public ShoppingCartViewModel ShoppingCartViewModel { get; set; }

        public CartController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            ShoppingCartViewModel = new ShoppingCartViewModel()
            {
                ListCart = _unitOfWork.ShoppingCart.GetAll(u => u.ApplicationUserId == claim.Value, includeProperties: "Product")
            };
            foreach(var cart in ShoppingCartViewModel.ListCart)
            {
                cart.Price = GetPriceBasedOnQuantity(cart.Count, cart.Product.Price, cart.Product.Price50, cart.Product.Price100);
                ShoppingCartViewModel.CartTotal+=(cart.Price * cart.Count);
            }
            return View(ShoppingCartViewModel);
        }

        public IActionResult Summary()
        {
            //var claimsIdentity = (ClaimsIdentity)User.Identity;
            //var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            //ShoppingCartViewModel = new ShoppingCartViewModel()
            //{
            //    ListCart = _unitOfWork.ShoppingCart.GetAll(u => u.ApplicationUserId == claim.Value, includeProperties: "Product")
            //};
            //foreach (var cart in ShoppingCartViewModel.ListCart)
            //{
            //    cart.Price = GetPriceBasedOnQuantity(cart.Count, cart.Product.Price, cart.Product.Price50, cart.Product.Price100);
            //    ShoppingCartViewModel.CartTotal += (cart.Price * cart.Count);
            //}
            //return View(ShoppingCartViewModel);
            return View();
        }

        public IActionResult Plus(int cartId)
        {
            var cart = _unitOfWork.ShoppingCart.GetFirstOrDefault(u=> u.Id == cartId);
            _unitOfWork.ShoppingCart.IncrementCount(cart, 1);
            _unitOfWork.Save();
            return RedirectToAction(nameof(Index));
        }
        public IActionResult Minus(int cartId)
        {
            var cart = _unitOfWork.ShoppingCart.GetFirstOrDefault(u => u.Id == cartId);
            if(cart.Count <= 1)
            {
                _unitOfWork.ShoppingCart.Remove(cart);
            }
            else
            {
                _unitOfWork.ShoppingCart.DecrementCount(cart, 1);
            }
            
            _unitOfWork.Save();
            return RedirectToAction(nameof(Index));
        }
        public IActionResult Remove(int cartId)
        {
            var cart = _unitOfWork.ShoppingCart.GetFirstOrDefault(u => u.Id == cartId);
            _unitOfWork.ShoppingCart.Remove(cart);
            _unitOfWork.Save();
            return RedirectToAction(nameof(Index));
        }

        private double GetPriceBasedOnQuantity(double quantity, double price, double price50, double price100)
        {
            if(quantity<=50)
            {
                return price;
            }
            else
            {
                if(quantity<=100)
                {
                    return price50;
                }
                return price100;
            }
        }
    }
}

AuxiPress_Project/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Toy Cars</title>
    <link rel="stylesheet" href="~/css/TestTheme.css"/>
    @*<link rel="stylesheet" href="~/css/ThemeClasse.css" />*@ @*Je rajoute mon theme telechargé*@
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css"
    <link rel="stylesheet" href="~/AuxiPress_Project.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.3/font/bootstrap-icons.css">
    
    <link rel="stylesheet" href="//cdn.datatables.net/1.12.1/css/jquery.dataTables.min.css"
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    @*<a class="navbar-brand" href="#">Menu</a>*@
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarColor03">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">        
              <a class="nav-link text-dark" asp-area="Customer" asp-controller="Home" asp-action="Index">Home</a>   
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Content Management</a>
          <div class="dropdown-menu">
              <a class="dropdown-item" asp-area="Admin" asp-controller="Category" asp-action="Index">Category</a>
              <a class="dropdown-item" asp-area="Admin" asp-controller="CarType" asp-action="Index">Toy Type</a>
              <a class="dropdown-item" asp-area="Admin" asp-controller="Product" asp-action="Index">Product</a>

          </div>
        </li>
        <li class="nav-item">
            <a class="nav-link" asp-area="Customer" asp-controller="Cart" asp-action="Index">
            <i class="bi bi-cart3"></i>
            </a>
        </li>
      </ul>

      <partial name="_LoginPartial"/>

@*      <form class="d-flex">
        <input class="form-control me-sm-2" type="text" placeholder="Search">
        <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
      </form>*@
    </div>
  </div>
</nav>

    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Toy Cars - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    @*Je modifie mon Script JS que je recupere sur le site Bootstrap !*@
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="//cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
     <script src="https://cdn.tiny.cloud/1/6xm3po1bo7yqiw9jak0a6oynjpzqw2ez31k7i1eherc3jldr/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script> @*Editeur de text intégré via l'API TINY MCE*@
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

AuxiPress_Project/Views/Shared/_Notification.cshtml
@if(TempData["Success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">toastr.success('@TempData["Success"]');</script>
}

@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">toastr.error('@TempData["error"]');</script>
 }